package:
  name: meteosatpy
  version: "0.0.3"

source:
  url: https://files.pythonhosted.org/packages/cc/ba/b4d26ea91efa167b0920b05a1aa95628bf02cb7fe7b284bcf8a23229a447/meteosatpy-0.0.3.tar.gz
  sha256: 7819659ab003eb0bed8fdfe254a5d58cbed47772d6ef403cfea2c95e257a4a86
  md5: b497634c7e5ccb693e41fb3af42f7071

build:
  number: 1
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python 3.9.*
    - pip
  run:
    - python
    - rasterio
    - xarray
    - geopandas
    - requests

test:
  imports:
    - meteosatpy
  requires:
    - python 

about:
  home: https://github.com/jusethCS/meteosatpy
  license: MIT
  license_family: MIT
  summary: Library designed for downloading and managing meteorological data sourced from satellites and global models.
  description: MeteoSatPy is a Python library designed for downloading and managing hydro-meteorological data sourced from satellites and global models. It offers users efficient access to near-real-time and historical weather conditions globally. With features for data acquisition, processing, and analysis. MeteoSatPy is a versatile tool for meteorological research, forecasting, and decision-making across various sectors.
