package:
  name: meteosatpy
  version: "0.0.2"

source:
  url: https://files.pythonhosted.org/packages/6c/fa/61e5ea8c64e91ef8effed923ab97a407bb5fa1c70d0db12cf86cbbafd238/meteosatpy-0.0.2.tar.gz
  sha256: 81119f97ad7786cc2c134844950d40fc23c79be5d14223d54bf32a91a46e7f4b
  md5: 58702e50922eeb74abc9bc676e412f42

build:
  number: 1
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python 3.9.*
    - pip
  run:
    - python
    - rasterio
    - xarray
    - geopandas

test:
  imports:
    - meteosatpy
  requires:
    - python 

about:
  home: https://github.com/jusethCS/meteosatpy
  license: MIT
  license_family: MIT
  summary: Library designed for downloading and managing meteorological data sourced from satellites and global models.
  description: MeteoSatPy is a Python library designed for downloading and managing hydro-meteorological data sourced from satellites and global models. It offers users efficient access to near-real-time and historical weather conditions globally. With features for data acquisition, processing, and analysis. MeteoSatPy is a versatile tool for meteorological research, forecasting, and decision-making across various sectors.
